> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy function 


###  Assignment 2
Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [40]:
# List of functions explained 
function1 = np.concatenate  
function2 = np.sin
function3 = np.median
function4 = np.reshape
function5 = np.bitwise_or

SyntaxError: invalid syntax (2434335014.py, line 5)

## Function 1 - np.concatenate 
np.concatenate function is used to add two arrays in which all the input array dimensions for the concatenation axis must match exactly.

In [15]:
# Example 1 - 
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In this example we are using concatenate function to join arr1 and arr2 along with x axis.
the array at index 0 and the array at index 1 have same size
In short, no of rows should match when concatenate along with axis=1.

In [12]:
# Example 2 - working

arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9],
        [10,15]]

np.concatenate((arr1, arr2), axis=0)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 8.,  9.],
       [10., 15.]])

In this example we are using concatenate function to join arr1 and arr2 along with y axis.
In the array at index 0 and the array at index 1 size should be same 
In short, no of column should match when concatenate along with axis=0.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

As we can clearly see in error size of array at 0 index in arr1 is not equal to size of array at 1 index in arr2

This function is used when we need to combine some result of two array to single arrays

In [17]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy-array-operations


'https://jovian.ai/satyanshu1925/numpy-array-operations'

## Function 2 - np.sin 
It changes the array elements values to sin(values)
It give value of sin in result

In [27]:
# Example 1 - working
arr  = np.array([[1,2,3,4],
               [5,15,6,10],
               [1,2,4,-5]])
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427,  0.65028784, -0.2794155 , -0.54402111],
       [ 0.84147098,  0.90929743, -0.7568025 ,  0.95892427]])

We can see it's providing result of the value by their sin values

In [28]:
# Example 2 - working
arr  = np.array([[1,2,3,-4],
               [5,-15,6.4,10],
               [1,2.,4,-5]])
np.cos(arr)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219, -0.75968791,  0.99318492, -0.83907153],
       [ 0.54030231, -0.41614684, -0.65364362,  0.28366219]])

We can see it's providing result of the value by their sin values.
Even when values are negative as well as float

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
arr  = np.array([["1",2,3,-4],
               [5,"-15",6,10.3],
               [1,2,4,"-5"]])
np.sin(arr)

TypeError: ufunc 'sin' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Explanation about example (why it breaks and how to fix it)
As we can see we can not pass any other values other than float and number.

Some closing comments about when to use this function.

In [30]:
jovian.commit(project="numpy-array-operations")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy-array-operations


'https://jovian.ai/satyanshu1925/numpy-array-operations'

## Function 3 -  np.median
used to compute the median along any specified axis.


In [36]:
# Example 1 - working
#1D array 
arr = np.array([20, 2, 7, 1, 34])

print("arr {} ".format(arr))
print("median of arr : {}".format(np.median(arr)) )

arr [20  2  7  1 34] 
median of arr : 7.0


It is providing the result of 1D array 

In [37]:
# Example 2 - working
# 2D array
arr = np.array([[14, 17, 12, 33, 44],
      [15, 6, 27, 8, 19],
      [23, 2, 54, 1, 4, ]])
  
print("\nmedian of arr, axis = None : ", np.median(arr))
  
print("\nmedian of arr, axis = 0 : ", np.median(arr, axis = 0))

print("\nmedian of arr, axis = 1 : ", np.median(arr, axis = 1))


median of arr, axis = None :  15.0

median of arr, axis = 0 :  [15.  6. 27.  8. 19.]

median of arr, axis = 1 :  [17. 15.  4.]


We calculated the median over the axis of the array

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
arr = [20, 2, "7", 1, "34"]

print("arr {} ".format(arr))
print("median of arr : {}".format(np.median(arr)) )

arr [20, 2, '7', 1, '34'] 


TypeError: cannot perform reduce with flexible type

Explanation about example (why it breaks and how to fix it)
As we can we if we pass any value other than numerical values it will be provide error

Some closing comments about when to use this function.

In [39]:
jovian.commit(project="numpy-array-operations")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy-array-operations


'https://jovian.ai/satyanshu1925/numpy-array-operations'

## Function 4 - np.reshape
The numpy. reshape() function allows us to reshape an array in Python.

In [46]:
# Example 1 - working
arr = np.array([12,34,45,65,76,334,2323,545,342,32,232,12])

np.reshape(arr,(3,4))

array([[  12,   34,   45,   65],
       [  76,  334, 2323,  545],
       [ 342,   32,  232,   12]])

Changing 1D array of size of 3 * 4 

In [54]:
# Example 2 - working
arr = np.array([[  12,   34,   45,   65],
               [  76,  334, 2323,  545],
               [ 342,   32,  232,   12],
               [  76,  334, 2323,  545]])
np.reshape(arr,16)

array([  12,   34,   45,   65,   76,  334, 2323,  545,  342,   32,  232,
         12,   76,  334, 2323,  545])

Changing 2D array of 4*4 into 1*16

In [55]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[  12,   34,   45,   65],
               [  76,  334, 2323,  545],
               [ 342,   32,  232,   12],
               [  76,  334, 2323,  545]])
np.reshape(arr,(1,8,9))

ValueError: cannot reshape array of size 16 into shape (1,8,9)

As we can see a ValueError occurs cannot reshape array of size 16 into shape (1,8,9)
we need to give the shape in which array can be reshaped

Some closing comments about when to use this function.

In [56]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy-array-operations


'https://jovian.ai/satyanshu1925/numpy-array-operations'

## Function 5 -  np.bitwise_or
np.bitwise_or() function is used to Compute the bit-wise OR of two array element-wise.

In [60]:
# Example 1 - working
arr1 = np.array(10)
arr2 = np.array(11)
print("Bitwise OR of {} and {} is {}".format(arr1,arr2,np.bitwise_or(arr1,arr2)))

Bitwise OR of 10 and 11 is 11


It perform bitwise or operation in 1D array 

In [61]:
# Example 2 - working
arr1 = np.array([2,7,13])
arr2 = np.array([4,9,11])
print("Bitwise OR of {} and {} is {}".format(arr1,arr2,np.bitwise_or(arr1,arr2)))

Bitwise OR of [ 2  7 13] and [ 4  9 11] is [ 6 15 15]


It is bitwise operation in 2D array

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([2,7,13])
arr2 = np.array([4,9,11,23,43])
print("Bitwise OR of {} and {} is {}".format(arr1,arr2,np.bitwise_or(arr1,arr2)))

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

As we can see it is providing a ValueError: operands could not be broadcast together with shapes (3,) (5,).
It can be fixed by passing right size of both the array 


Some closing comments about when to use this function.

In [63]:
jovian.commit(project="numpy-array-operations")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy-array-operations


'https://jovian.ai/satyanshu1925/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy Geeksforgeeks tutorial : https://www.geeksforgeeks.org/numpy-in-python-set-1-introduction/

In [ ]:
jovian.commit(project="numpy-array-operations")

<IPython.core.display.Javascript object>