# numpy

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian
# Execute this to save new versions of the notebook
jovian.commit(project="numpy")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy


'https://jovian.ai/satyanshu1925/numpy'

## using python list

In [3]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [4]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [5]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights = [w1, w2, w3]

In [8]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(unova, weights)

74.9

## Going from python lists to Numpy array

In [12]:
import numpy as np

In [13]:
kanto = np.array([73,67,43])

In [14]:
kanto

array([73, 67, 43])

In [15]:
weights = np.array([w1,w2,w3])

In [16]:
weights

array([0.3, 0.2, 0.5])

In [17]:
type(kanto)

numpy.ndarray

In [18]:
type(weights)

numpy.ndarray

## Operating on Numpy arrays

In [19]:
# help(np.dot)

In [20]:
np.dot(kanto,weights)

56.8

In [21]:
(kanto*weights).sum()

56.8

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [23]:
arr1*arr2

array([ 4, 10, 18])

In [24]:
arr2.sum()

15

## Benefits of using Numpy arrays

In [25]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [26]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 163 ms, sys: 1.45 ms, total: 165 ms
Wall time: 164 ms


833332333333500000

In [27]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.89 ms, sys: 0 ns, total: 2.89 ms
Wall time: 1.76 ms


833332333333500000

In [28]:
jovian.commit(project="numpy")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy


'https://jovian.ai/satyanshu1925/numpy'

## Multi-dimensional Numpy arrays

In [29]:
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

In [30]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [31]:
climate_data.shape

(5, 3)

In [32]:
weights

array([0.3, 0.2, 0.5])

In [33]:
weights.shape

(3,)

In [34]:
arr3 = np.array([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
    [17,18,19.6]]])

In [35]:
arr3.shape

(2, 2, 3)

In [36]:
weights.dtype

dtype('float64')

In [37]:
arr3.dtype

dtype('float64')

In [38]:
%%time
np.matmul(climate_data,weights)

CPU times: user 283 µs, sys: 65 µs, total: 348 µs
Wall time: 417 µs


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [39]:
%%time
climate_data @ weights

CPU times: user 245 µs, sys: 56 µs, total: 301 µs
Wall time: 309 µs


array([56.8, 76.9, 81.9, 57.7, 74.9])

## working with CSV data files
csv - comma separated values

In [40]:
import urllib.request


In [41]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f9e490ece50>)

In [42]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [43]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [44]:
climate_data.shape

(10000, 3)

In [45]:
weights = np.array([0.3,0.2,0.5])

In [46]:
yields = climate_data @ weights

In [47]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [48]:
yields.shape

(10000,)

In [49]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [50]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [51]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt='%.2f',
          delimiter=',',
          header='temperature,rainfall,humidity,yeild_apples',
          comments='')

In [52]:
jovian.commit(project="numpy")

<IPython.core.display.Javascript object>

[jovian] Updating notebook "satyanshu1925/numpy" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/satyanshu1925/numpy


'https://jovian.ai/satyanshu1925/numpy'

## Arithmetic operations, broadcasting and comparison

In [53]:
arr_1 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [54]:
arr_2 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]])

In [55]:
#Adding a scaler
arr_1 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [56]:
# Element-wise subtraction
arr_2 - arr_1

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [57]:
# Divison by scaler
arr_2 / 2

array([[5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. ],
       [9.5, 5.5, 6. , 6.5]])

In [58]:
# Element-wise multiplication
arr_1*arr_2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [59]:
# Modulus with scaler
arr2%4

TypeError: unsupported operand type(s) for %: 'list' and 'int'

### Array Broadcasting

In [ ]:
arr_2 = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,1,2,3]])

In [ ]:
arr_2.shape

In [ ]:
arr4 = np.array([4,5,6,7])

In [ ]:
arr4.shape

In [ ]:
arr2 + arr4

In [ ]:
arr5 = np.array([7,8])

In [ ]:
arr5.shape

In [ ]:
# arr_2 + arr5

### Array Comparison

In [ ]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,5]])

In [ ]:
arr1 == arr2

In [ ]:
arr1 != arr2

In [ ]:
arr1 >= arr2

In [ ]:
arr1 < arr2

In [ ]:
(arr1 == arr2).sum()

### Array indexing and slicing

In [ ]:
arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,19]],
    
    [[15,16,17,21],
    [63,92,36,18]],
    
    [[98,32,81,23],
    [17,18,19.5,43]]
])

In [ ]:
arr3.shape

In [ ]:
# single Element
arr3[1,1,2]

In [ ]:
# Subarray using ranges
arr3[1:,0:1,:2]

In [ ]:
# Mixing indices and ranges
arr3[1:,1,3]

In [ ]:
# Mixing indices and ranges
arr3[1:,1,:3]

In [ ]:
#using fewer indices
arr3[1]

In [ ]:
# using fewer indices 
arr3[:2,1]

In [ ]:
# Using too many indices
# arr3[1,3,2,1]

### Other ways of creating Numpy arrays

In [ ]:
# All Zeros
np.zeros((3,2))

In [ ]:
#All ones
np.ones([2,2,3])

In [ ]:
# Identity matrix
np.eye(3)

In [ ]:
#Random matrix
np.random.rand(2,3)

In [ ]:
 # rand vs. randn - what's the difference?
np.random.randn(2,3)

In [ ]:
#Fixed value
np.full([2,3],42)

In [ ]:
#range with start, end and step
np.arange(10,90,3)

In [ ]:
# Equally spaced numver in range
np.linspace(3,27,9)

In [ ]:
jovian.commit(project="numpy")